{% set name = "beangulp" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beangulp-{{ version }}.tar.gz
  sha256: 1fd131c76e5fda8c056efcc2f8a0d2bf5cd8141ef29060762601358f80f4a9b5

build:
  number: 0

requirements:
  host:
    - python
    - setuptools >=60.0
    - pip
  run:
    - python
    - beancount >=2.3.5
    - beautifulsoup4
    - chardet
    - click >8.0
    - lxml
    - petl
    - python-magic >=0.4.12  # [not win]

# This package comes with pytest fixtures, but they require data files that
# aren't included in the source distribution.
test:
  imports:
    - beangulp
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Importers Framework for Beancount
  home: https://github.com/beancount/beangulp
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
